# Generated by Django 3.1.2 on 2023-03-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_customerprofile_techincalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('serialnumber', models.CharField(max_length=150)),
                ('yearofmade', models.CharField(max_length=150)),
                ('deviceimage', models.ImageField(upload_to='pic')),
                ('devicemodel', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('workrate', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('problemimage', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.customerprofile')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.devices')),
                ('techincal', models.ManyToManyField(to='Login.TechincalProfile')),
            ],
        ),
    ]
