# Generated by Django 3.1.2 on 2023-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_devices_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='mancontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='problemimage',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
