# Generated by Django 3.1.2 on 2023-03-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20230315_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='device',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='mancontact',
        ),
        migrations.AddField(
            model_name='devices',
            name='oredr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Login.orders'),
        ),
        migrations.AddField(
            model_name='mancontact',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Login.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Login.customerprofile'),
        ),
    ]
