# Generated by Django 3.1.2 on 2023-03-15 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_auto_20230315_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='techincal',
        ),
        migrations.AddField(
            model_name='orders',
            name='techincal',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Login.techincalprofile'),
        ),
    ]
