# Generated by Django 3.2.18 on 2023-03-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_auto_20230325_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ordernumber',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='problemimage',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='techincal',
        ),
        migrations.CreateModel(
            name='image_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemimage', models.ImageField(upload_to='pic')),
                ('ordr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.orders')),
            ],
        ),
    ]
