# Generated by Django 3.2.18 on 2023-03-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_auto_20230325_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_orders',
            old_name='ordr',
            new_name='order',
        ),
    ]
